src/digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView
import posts.views

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$', posts.views.home, name="post_home"),
    url(r'^blog/(?P<post_id>[0-9]+)/$', posts.views.post_details, name="post_detail"),
    url(r'^blog/(?P<slug>[\w-]+)/$', posts.views.post_details, name="post_detail_slug"),
    url(r'^library/', UserLibraryListView.as_view(), name='library'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^tags/', include("tags.urls", namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sellers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from products.views import (
		ProductCreateView,
		ProductUpdateView,
		SellerProductListView
	)

from .views import (
        SellerDashboard,
        SellerProductDetailRedirectView,
        SellerTransactionListView
        )

urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transactions/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'), #sellers:product_list
    url(r'^products/(?P<pk>\d+)/$', SellerProductDetailRedirectView.as_view()),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
]

src/tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagListView,
        TagDetailView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- You are here: /base.html -->
<html>
<head>
  <!-- JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.0/js/mdb.min.js"></script>-->
  <!-- jquery stylesheet -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- font awesome cdn -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
  <!-- Bootswatch Theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" type="text/css" />
  <!-- base.css -->
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" href="{% static 'css/heart.css' %}" />
  <!-- yamm megamenu -->
  <link href="{% static 'css/yamm.css' %}" rel="stylesheet" type="text/css">
  <!-- custom fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:600,700" rel="stylesheet">
  <!-- material design cdn -->
  <!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.0/css/mdb.min.css" rel="stylesheet">-->


</head>
<body>

    {% include "header.html" %}

    {% block content %}
    {% endblock content %}

    {% include "footer.html" %}

<!-- scripts -->
<script>
  $(document).on('click', '.yamm .dropdown-menu', function(e) {
    e.stopPropagation()
  })
</script>
<!-- ajax -->
<script src="{% static 'js/django.csrf.js' %}"></script>
<!-- ajax call -->
<script>
  $(document).ready(function(){
    {% block jquery %}

    {% endblock jquery %}
  })
</script>

</body>
</html>

src/templates/create_view.html
{% extends "base.html" %}
{% block content %}

{% if "seller" in request.path %}
  {% include "dashboard/seller_header.html" %}
{% endif %}
<!-- You are here: /create_view.html -->

<div class="container">

  <div class="page-header">
    <h1> List an Item </h1>
  </div>

  <div class="row">
    <div class="col-sm-8">
      {% include "form_include.html" with form=form submit_btn="Create Product" %}
      <br />
    </div>
  </div>

</div>
{% endblock content %}

src/templates/detail_view.html
{% extends "base.html" %}
<!-- You are here: /detail_view.html -->

{% block content %}
<br />
<div class="container">
  <!-- START: Photo Section -->
  <div class="col-sm-8">
    <img class="img-responsive" src="{{ product.media.url }}" alt="{{ product.title }}" />
  </div>
  <!-- END: Photo Section -->

  <!-- START: Product Details -->
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>{{ product.brand }}</h3>
        <h1> {{ product.title }} </h1>
      </div>

      <ul class="list-group">
        <li class="list-group-item">
          <p>Size: {{ product.size }}</p>
          <h4>Price: {{ product.price }}</h4>
          <p>Retail Price: {{ product.msrp }}</p>
          <a class="btn btn-primary btn-lg">Add to Bag</a>
        </li>
        <li class="list-group-item">
          <h4>Condition</h4>
          <p>With Retail Tags? {{ product.conditionTags }}</p>
          <p>Signs of Wear? {{ product.conditionWear }}</p>
        </li>
        <li class="list-group-item">
          <h4>Description</h4>
          <p>{{ product.style }}</p>
          <p>{{ product.description }}</p>
          <a class="btn btn-default">Request More Information</a>
        </li>
      </ul>

    </div>
  </div>
  <!-- END: Product Details -->
</div>

{% endblock content %}

src/templates/footer.html
<footer id="footer">
  <div class="container">

    <div class="row">
      <div class="text-center">
        <ul class="list-unstyled">
          <li><strong>one more again</strong></li>
          <li>San Francisco, CA</li>
          <li><br /></li>
          <li>
            <ul class="list-inline">
              <li><a href="https://www.facebook.com/goonemoreagain/"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a></li>
              <li><a href="https://www.twitter.com/goonemoreagain/"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a></li>
              <li><a href="https://www.instagram.com/goonemoreagain/"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></li>
            </ul>
          </li>
          <li><br /></li>
          <li>&copy; Copyright 2017 Continua Apparel Corporation.  All rights reserved.</li>
        </ul>
      </div>
    </div>

  </div>
</footer>

src/templates/form_include.html
<!-- You are here: /form_include.html -->
<form method="POST" action="">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-default" type='submit' value='{{ submit_btn }}' />
</form>

src/templates/header.html
<!-- You are here: header.html -->
<!-- primary header:util -->
<nav class="navbar navbar-default" id="main-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "dashboard" %}">one more again</a>
    </div>
    <div class="collapse navbar-collapse" id="main-top-nav">
      <ul class="nav navbar-nav">

        <!-- <li><a href="{% url "tags:list" %}">Tags</a></li>
        <li><a href="{% url "products:list" %}">Products</a></li> -->

<!-- need to activate for global search -->
        <form method="GET" action="" class="navbar-form navbar-left">
          <div class="input-group add-on">
            <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}" />
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search" alt="Search"></i>
              </button>
            </div>
          </div>
        </form>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;{{ user }} </a>
          <ul class="dropdown-menu">
            <li><a href="{% url "sellers:dashboard" %}">Dashboard</a></li>
            <li><a href="{% url "sellers:product_list" %}">Active Listings</a></li>
            <li><a href="{% url "sellers:transactions" %}">Sales</a></li>
            <li><a href="{% url "library" %}">Purchases</a></li>
            <li class="divider"></li>
            <li><a href="{% url "sellers:product_create" %}">Add a Listing &nbsp;<i class="fa fa-plus-square-o" aria-hidden="true"></i></a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="/products/add"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;&nbsp;&nbsp;Login</a></li>
        {% endif %}
        <li><a href="/products/add"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></a></li>
      </ul>

    </div>
  </div>
</nav>

<!-- secondary header:shopping -->
<nav class="navbar yamm navbar-inverse" id="main-nav"  role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">MENU</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="main-collapse-nav">
      <ul class="nav navbar-nav">
        <li><a href="{% url "tags:list" %}">Tags</a></li>
        <li><a href="{% url "products:list" %}">Products</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clothing&nbsp;<span class="caret"></span></a>
          <ul class="dropdown-menu col-sm-8">
            <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-3 list-unstyled">
                    <li class="disabled"><h5>Departments</h5></li>
                    <li><a href="#">Leotards</a></li>
                    <li><a href="#">Unitards</a></li>
                    <li><a href="#">Skirts</a></li>
                    <li><a href="#">Dresses</a></li>
                    <li><a href="#">Tops</a></li>
                    <li><a href="#">Sweaters</a></li>
                    <li><a href="#">Bottoms</a></li>
                  </div>
                  <div class="col-sm-3 list-unstyled">
                    <li class="disabled"><h5>Brands</h5></li>
                    {% for instance in products|slice:":10" %}
                      <li><a href="{{ instance.get_absolute_url }}" >{{ instance.brand }}</a></li>
                    {% endfor %}
                    <!-- <li><a href="#">Bloch</a></li>
                    <li><a href="#">Capezio</a></li>
                    <li><a href="#">Sansha</a></li>
                    <li><a href="#">Mirella</a></li>
                    <li><a href="#">Curtain Call</a></li>
                    <li><a href="#">Body Wrappers</a></li>
                    <li><a href="#">Bunheads</a></li>
                    <li><a href="#">Gaynor Minden</a></li>
                    <li><a href="#">Nike</a></li>
                    <li><a href="#">Under Armour</a></li>
                    <li><a href="#">Adidas</a></li>
                    <li><a href="#">Lululemon</a></li> -->
                  </div>
                  <div class="col-sm-3 list-unstyled">
                    <li class="disabled"><h5>Dance Type</h5></li>
                    <li><a href="#">Ballet</a></li>
                    <li><a href="#">Tap</a></li>
                    <li><a href="#">Jazz</a></li>
                    <li><a href="#">Lyrical</a></li>
                    <li><a href="#">Hip-Hop</a></li>
                    <li><a href="#">Belly Dancing</a></li>
                    <li><a href="#">Ballroom</a></li>
                    <li><a href="#">Bollywood</a></li>
                    <li><a href="#">Tango</a></li>
                    <li><a href="#">Afro-Brazilian</a></li>
                    <li><a href="#">Flamenco</a></li>
                  </div>
                  <div class="col-sm-3 list-unstyled">
                    <img class="img-responsive thumbnail" src="/media/warm-up-gear/association-1644452_1920.jpg" alt="spotlight trend image" />
                    <li class="disabled"><h5>Spotlight: Warm-up Gear</h5></li>
                    <a class="btn btn-default" href="/blog/2">Shop Now</a>
                  </div>
                </div> <!-- close row -->
              </div> <!-- close yamm-content -->
          </ul>
        </li>
        <li><a href="{% url "products:list" %}">Shoes</a></li>
        <li><a href="{% url "products:list" %}">Accessories</a></li>
        <li><a href="{% url "products:list" %}">Girls</a></li>
        <li><a href="{% url "products:list" %}">Boys/Men</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/products/add">Start Selling</a></li>
      </ul>
    </div>
  </div>
</nav>

src/templates/list_view.html
{% extends "base.html" %}
<!-- You are here: /list_view.html -->

{% block content %}

<div class="page-header">
  <h1> List View </h1>
</div>

{{ queryset }}

{% endblock content %}

src/templates/update_view.html
{% extends "base.html" %}
{% block content %}

{% if "seller" in request.path %}
  {% include "dashboard/seller_header.html" %}
{% endif %}

<!-- You are here: /update_view.html -->
<div class="container">

<div class="page-header">
  <h1> Make a Change to {{ product.title }} </h1>
</div>

<div class="col-sm-8">
{% include "form_include.html" with form=form submit_btn="Update Product" %}
</div>
<br/>
</div>
{% endblock content %}