src/digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView
import posts.views

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$', posts.views.home, name="post_home"),
    url(r'^blog/(?P<post_id>[0-9]+)/$', posts.views.post_details, name="post_detail"),
    url(r'^blog/(?P<slug>[\w-]+)/$', posts.views.post_details, name="post_detail_slug"),
    url(r'^library/', UserLibraryListView.as_view(), name='library'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^tags/', include("tags.urls", namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

from .views import (
        ProductDetailView,
        ProductLikesAjaxView,
        ProductListView,
        ProductCreateView,
        ProductUpdateView,
        VendorListView,
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^vendor/$', RedirectView.as_view(pattern_name='products:list'), name='vendor_list'),
    url(r'^vendor/(?P<vendor_name>[\w.@+-]+)/$', VendorListView.as_view(), name='vendor_detail'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail_slug'),
    url(r'^(?P<pk>\d+)/edit$', ProductUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/edit/$', ProductUpdateView.as_view(), name='update_slug'),
    url(r'^ajax/likes/$', ProductLikesAjaxView.as_view(), name='ajax_likes'),
]

src/tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagListView,
        TagDetailView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

src/billing/models.py
from django.conf import settings
from django.db import models

from products.models import Product

class Transaction(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	product = models.ForeignKey(Product)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=8.88, null=True,)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	success = models.BooleanField(default=True)
	# transaction_id_payment_system = Braintree / Stripe
	# payment_method
	# last_four

	def __unicode__(self):
		return "%s" %(self.id)

src/products/views.py
from django.db.models import Q, F, Avg, Count
from django.core.urlresolvers import reverse
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from analytics.models import TagView

from digitalmarket.mixins import (
        MultiSlugMixin,
        LoginRequiredMixin,
        StaffRequiredMixin,
        AjaxRequiredMixin
        )

from sellers.models import SellerAccount
from sellers.mixins import SellerAccountMixin
from tags.models import Tag

from .forms import ProductAddForm, ProductModelForm
from .mixins import ProductManagerMixin
from .models import Product, ProductLikes, MyProducts


class ProductLikesAjaxView(AjaxRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return JsonResponse({}, status=401)
        # credit card required **

        user = request.user
        product_id = request.POST.get("product_id")
        rating_value = request.POST.get("rating_value")
        exists = Product.objects.filter(id=product_id).exists()
        if not exists:
            return JsonResponse({}, status=404)

        try:
            product_obj = Product.object.get(id=product_id)
        except:
            product_obj = Product.objects.filter(id=product_id).first()

        rating_obj, rating_obj_created = ProductLikes.objects.get_or_create(
                user=user,
                product=product_obj
                )
        try:
            rating_obj = ProductLikes.objects.get(user=user, product=product_obj)
        except ProductLikes.MultipleObjectsReturned:
            rating_obj = ProductLikes.objects.filter(user=user, product=product_obj).first()
        except:
            # rating_obj = ProductLikes.objects.create(user=user, product=product_obj)
            rating_obj = ProductLikes()
            rating_obj.user = user
            rating_obj.product = product_obj
        rating_obj.rating = int(rating_value)
        myproducts = user.myproducts.products.all()
        if product_obj in myproducts:
            rating_obj.verified = True
        rating_obj.save()

        data = {
            "success": True
        }
        return JsonResponse(data)


class ProductCreateView(SellerAccountMixin, CreateView):
    model = Product
    template_name = "create_view.html"
    form_class = ProductModelForm

    def form_valid(self, form):
        seller = self.get_account()
        form.instance.seller = seller
        valid_data = super(ProductCreateView, self).form_valid(form)
        tags = form.cleaned_data.get("tags")
        if tags:
            tags_list = tags.split(",")
            for tag in tags_list:
                if not tag == " ":
                    new_tags = Tag.objects.get_or_create(title=str(tag).strip())[0]
                    new_tags.products.add(form.instance)
        return valid_data

    # this makes it return user profile - but user profile does not exist yet
    def get_success_url(self):
        return reverse("products:list")

class ProductUpdateView(ProductManagerMixin, MultiSlugMixin, UpdateView):
    model = Product
    template_name = "update_view.html"
    form_class = ProductModelForm

    def get_initial(self):
        initial = super(ProductUpdateView, self).get_initial()
        tags = self.get_object().tag_set.all()
        initial["tags"] = ", ".join([x.title for x in tags])
        return initial

    def form_valid(self, form):
        valid_data = super(ProductUpdateView, self).form_valid(form)
        tags = form.cleaned_data.get("tags")
        # obj.tag_set.clear()
        if tags:
            tags_list = tags.split(",")
            obj = self.get_object()
            obj.tag_set.clear()
            for tag in tags_list:
                if not tag == " ":
                    new_tags = Tag.objects.get_or_create(title=str(tag).strip())[0]
                    new_tags.products.add(self.get_object())
        return valid_data

class ProductDetailView(MultiSlugMixin, DetailView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        obj = self.get_object()
        tags = obj.tag_set.all()
        rating_sum = obj.productlikes_set.aggregate(Count("rating"))
        context["rating_sum"] = rating_sum
        if self.request.user.is_authenticated():
            rating_obj = ProductLikes.objects.filter(user=self.request.user, product=obj)
            if rating_obj.exists():
                context['my_rating'] = rating_obj.first().rating
            for tag in tags:
                new_view = TagView.objects.add_count(self.request.user, tag)
        return context

class VendorListView(ListView):
    model = Product
    template_name = 'products/product_list.html'

    def get_object(self):
        username= self.kwargs.get("vendor_name")
        seller = get_object_or_404(SellerAccount, user__username=username)
        return seller

    def get_context_data(self, *args, **kwargs):
        context = super(VendorListView, self).get_context_data(*args, **kwargs)
        context["vendor_name"] = str(self.get_object().user.username)
        return context

	def get_queryset(self, *args, **kwargs):
		seller = self.get_object()
		qs = super(VendorListView, self).get_queryset(**kwargs).filter(seller=seller)
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
				).order_by("title")
		return qs



class SellerProductListView(SellerAccountMixin, ListView):
    model = Product
    template_name = "sellers/product_list_view.html"

    def get_queryset(self, *args, **kwargs):
        qs = super(SellerProductListView, self).get_queryset(**kwargs)
        qs = qs.filter(seller=self.request.user)
        query = self.request.GET.get("q")
        if query:
            qs = qs.filter(
                    Q(title__icontains=query)|
                    Q(description__icontains=query)
                ).order_by("title")
        return qs

class ProductListView(ListView):
    model = Product

    def get_queryset(self, *args, **kwargs):
        qs = super(ProductListView, self).get_queryset(**kwargs)
        query = self.request.GET.get("q")
        if query:
            qs = qs.filter(
                    Q(title__icontains=query)|
                    Q(description__icontains=query)
                ).order_by("-pk")
        return qs

class UserLibraryListView(LoginRequiredMixin, ListView):
    model = MyProducts
    template_name = "products/library_list.html"

    def get_queryset(self, *args, **kwargs):
        obj = MyProducts.objects.get_or_create(user=self.request.user)[0]
        qs = obj.products.all()
        query = self.request.GET.get("q")
        if query:
            qs = qs.filter(
                    Q(title__icontains=query)|
                    Q(description__icontains=query)
                ).order_by("-pk")
        return qs

def create_view(request):
    form = ProductModelForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.sale_price = instance.price
        instance.save()
    template = "create_view.html"
    context = {
            "form" : form,
        }
    return render(request, template, context)

def update_view(request, object_id=None):
    product = get_object_or_404(Product, id=object_id)
    form = ProductModelForm(request.POST or None, instance=product)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    template = "update_view.html"
    context = {
        "product" : product,
        "form" : form,
    }
    return render(request, template, context)

def detail_slug_view(request, slug=None):
	product = Product.objects.get(slug=slug)
	try:
		product = get_object_or_404(Product, slug=slug)
	except Product.MultipleObjectsReturned:
		product = Product.objects.filter(slug=slug).order_by("-title").first()
	# print slug
	# product = 1
	template = "detail_view.html"
	context = {
		"object": product
		}
	return render(request, template, context)

def detail_view(request, object_id=None):
    product = get_object_or_404(Product, id=object_id)
    template = "detail_view.html"
    context = {
        "product" : product
    }
    return render(request, template, context)

def list_view(request):
    # multi item
    print request
    queryset = Product.objects.all()
    template = "list_view.html"
    context = {
        "queryset" : queryset
    }
    return render(request, template, context)

src/templates/products/library_list.html
{% extends "base.html" %}
{% block content %}

{% include "dashboard/seller_header.html" %}

<!-- You are here: /products/library_list.html -->
<div class="container">

<div class="page-header">
  <div id="list-sidebar" class="col-sm-4 pull-right">
    <form method="GET" action="">
      <div class="input-group add-on">
        <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}" />
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search" alt="Search"></i>
          </button>
        </div>
      </div>
    </form>
  </div>

  <h1>Purchased Products</h1>
</div>


<div class="row">
  <div id="list-display" class="col-sm-12">
  {% include "products/product_result.html" with object_list=object  %}
  </div>

</div><!-- end row -->

</div><!-- end container -->
{% endblock content %}

src/templates/products/product_detail.html
{% extends "base.html" %}

<script>
$(document).ready(function(){
{% block jquery %}
$(".rating input[value='{{ my_rating }}']").attr("checked", "checked");

$(".rating input[type='radio']").click(function(event){
  var inputValue = $(this).val()
  console.log(inputValue)
  var request = $.ajax({
    method: "POST",
    url: "{% url 'products:ajax_likes' %}",
    data: {
      product_id: "{{ object.id }}",
      rating_value: inputValue,
    }
  })
  request.done(function(data){
  })
  request.fail(function(jqXHR, textStatus){
    if (jqXHR.status == 404) {
      alert("Page not found!")
    } else if (jqXHR.status == 401) {
      alert("You must be logged in to do this.")
    } else {
      alert("There was an error with your request. Please try again.")
    }
  })
})

$("#add-to-cart-btn").click(function(event){
	event.preventDefault()
  var purchaseBtn = $(this)
	$("#cart-confirm").fadeIn("300")
	$("#cart-confirm").dialog({
		resizable: false,
		height: 250,
		width: 350,
		modal: true,
		buttons: {
			1: {
				id: "close",
				text: "Confirm",
				click: function(){
          var request = $.ajax({
						method: "POST",
						url: "{% url 'checkout' %}",
						data: {
							product_id: "{{ object.id }}",
						}
					})
					request.done(function(data){
            purchaseBtn.before("<a class='btn btn-success btn-lg'>Added to cart!</a>")
						purchaseBtn.fadeOut(0)
					})
					request.fail(function(jqXHR, textStatus){
						if (jqXHR.status == 404) {
							alert("Page not found!")
						} else if (jqXHR.status == 403) {
							alert("You must be logged in to do this.")
						} else {
							alert("There was an error with your request. Please try again.")
						}
					})

          $(this).dialog("close")
				},
				class: "buy-btn"
			},
			2: {
				id: "close",
				text: "Cancel",
				click: function(){
					$(this).dialog("close")
				},
				class: "cancel-btn"
			}
		}
	})
})
{% endblock jquery %}
})
</script>

{% block content %}
<!-- START: Photo Section -->
<br />
<div class="container" id="product-detail-view">
  <div id="photo-detail-image">
    <div class="col-sm-6 col-sm-offset-2">
      {% if product.media %}
        <img class="img-responsive thumbnail" src="{{ product.media.url }}" alt="{{ product.title }}" />
      {% endif %}
    </div>
  </div>
  <!-- END: Photo Section -->

  <!-- START: Product Details -->

  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
          <div class="rating">
            <input type="radio" id="heart" name="rating" value="1" />
            <span class="badge pull-right">{{ rating_sum.rating__count }}</span>
            <label for="heart" title="Like!"></label>
          </div>

        {% if product.transaction_set.count > 0 %}
          <h2><span class="label label-default"> Sold out </span></h2>
        {% endif %}
        <h3>{{ product.brand }}</h3>
        <h1> {{ product.title }} </h1>
      </div>

      <ul class="list-group">
        <li class="list-group-item">
          <p>Size: {{ product.size }}</p>
          <h4>Price: {{ product.get_html_price|safe }}</h4>
          <p>Retail Price: {{ product.msrp }}</p>

        {% if request.user.is_authenticated and product.user != user and object not in request.user.myproducts.products.all and product.transaction_set.count == 0 and product.seller != user %}
          <a class="btn btn-primary btn-lg" id="add-to-cart-btn" href="#">Add to Cart</a>
          <br /><br />
          <div id="cart-confirm" class="alert alert-success" title="Add this item to your Cart?" style="display:none;">
            <p>Added to Cart</p>
            <p>This item will remain reserved in your cart for the next 10 minutes!</p>
          </div>

        {% elif object in request.user.myproducts.products.all %}
        <a class="btn btn-success btn-lg" href="#">Congrats! You own this!</a>
        <!-- send user to their "my products" page -->
        {% else %}
        {% endif %}

        </li>
        <li class="list-group-item">
          <h4>Condition</h4>
          <p>With Retail Tags? {{ product.conditionTags }}</p>
          <p>Signs of Wear? {{ product.conditionWear }}</p>
        </li>
        <li class="list-group-item">
          <h4>Description</h4>
          <p>{{ product.style }}</p>
          <p>{{ product.description }}</p>
          {% if request.user.is_authenticated and product.user != user and object not in request.user.myproducts.products.all %}
            <a class="btn btn-default">Request More Information</a>
          {% else %}
          {% endif %}
        </li>
        <li class="list-group-item">
          <h4>More from this Seller</h4>
          <p><a href="{{ seller.get_absolute_url }}">{{ seller.user.username }}</a></p>
        </li>
      </ul>

    </div>
  </div>
</div>
<!-- END: Product Details -->

{% endblock content %}

src/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
<!-- You are here: /products/product_list.html -->
<div class="container">

<div class="page-header">
  <h1>List of Products</h1>
</div>

<div class="row">

  <div id="list-sidebar" class="col-sm-3">
    <form method="GET" action="">
      <div class="input-group add-on">
        <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}" />
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search" alt="Search"></i>
          </button>
        </div>
      </div>
    </form>
  </div>

  <div id="list-display" class="col-sm-9">
  {% include "products/product_result.html" with object_list=object  %}
  </div>

</div><!-- end row -->

</div><!-- end container -->
{% endblock content %}

src/templates/products/product_result.html
<!-- You are here: products/product_result.html -->
{% load get_thumbnail %}

{% for instance in product_list %}
  {% if forloop.first %}<div class="row">{% endif %}

{% if "seller" in request.path %}
<div class="col-sm-3" id="product-instance">
{% else %}
<div class="col-sm-4" id="product-instance">
{% endif %}
  <a href="{{ instance.get_absolute_url }}" >
    <div class="panel panel-default">
      <div class="panel-heading">
        {% if instance.transaction_set.count > 0 %}
        <span class="label label-default">Sold out</span>
        {% endif %}
        <!-- slice to show only one thumbnail in the set -->
        {% if instance|get_thumbnail:"sd" %}
          {% if instance.transaction_set.count > 0 %}
          <img class="img-responsive sold-img" src="{{ instance|get_thumbnail:"sd" }}" alt="{{ instance }}" />
          {% else %}
          <img class="img-responsive" src="{{ instance|get_thumbnail:"sd" }}" alt="{{ instance }}" />
          {% endif %}
        {% endif %}
      </div>
      <div class="panel-body">
        <h5>{{ instance.brand }}</h5>
        <p>{{ instance }}</p>
        <p class="listing-price">{{ instance.get_html_price|safe }}</p>
        <p>Size: {{ instance.size }}</p>
      </div>
    </div>
  </a>
</div>
{% if "seller" in request.path %}
{% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
{% if forloop.last %}</div>{% endif %}
{% else %}
  {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
  {% if forloop.last %}</div>{% endif %}
{% endif %}
  {% empty %}
      <p>No products yet!  Check back soon!</p>
  {% endfor %}