src/digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutTestView, CheckoutAjaxView
from dashboard.views import DashboardView
from products.views import UserLibraryListView
import posts.views

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^test/$', CheckoutTestView.as_view(), name='test'),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$', posts.views.home, name="post_home"),
    url(r'^blog/(?P<post_id>[0-9]+)/$', posts.views.post_details, name="post_detail"),
    url(r'^blog/(?P<slug>[\w-]+)/$', posts.views.post_details, name="post_detail_slug"),
    url(r'^library/', UserLibraryListView.as_view(), name='library'),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^tags/', include("tags.urls", namespace='tags')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sellers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from products.views import (
		ProductCreateView,
		ProductUpdateView,
		SellerProductListView
	)

from .views import (
        SellerDashboard,
        SellerProductDetailRedirectView,
        SellerTransactionListView
        )

urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transactions/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'), #sellers:product_list
    url(r'^products/(?P<pk>\d+)/$', SellerProductDetailRedirectView.as_view()),
    url(r'^products/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
]

src/tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        TagListView,
        TagDetailView,
        )

urlpatterns = [
    url(r'^$', TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

src/billing/models.py
from django.conf import settings
from django.db import models

from products.models import Product

class Transaction(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	product = models.ForeignKey(Product)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=8.88, null=True,)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	success = models.BooleanField(default=True)
	# transaction_id_payment_system = Braintree / Stripe
	# payment_method
	# last_four

	def __unicode__(self):
		return "%s" %(self.id)

src/dashboard/models.py
from django.db import models

# Create your models here.

src/sellers/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class SellerAccount(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="manager_sellers", blank=True)
	active = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __unicode__(self):
		return str(self.user.username)

	def get_absolute_url(self):
		return reverse("products:vendor_detail", kwargs={"vendor_name": self.user.username})

src/sellers/forms.py
from django import forms


class NewSellerForm(forms.Form):
	agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

src/dashboard/views.py
import random

from django.views.generic import View
from django.shortcuts import render

from products.models import Product
from posts.models import Post

class DashboardView(View):
    def get(self, request, *args, **kwargs):
        tag_views = None
        products = None
        posts = None
        queryset = Post.objects.all()
        queryset = queryset[:2]

        top_tags = None
        try:
            tag_views = request.user.tagview_set.all().order_by("-count")
        except:
            pass

        owned = None

        try:
            owned = request.user.myproducts.products.all()
        except:
            pass

        if tag_views:
            top_tags = [x.tag for x in tag_views]
            products = Product.objects.filter(tag__in=top_tags)
            if owned:
                products = products.exclude(pk__in=owned)

            if products.count() < 10:
                products = Product.objects.all().order_by("?")
                if owned:
                    products = products.exclude(pk__in=owned)
                products = products[:3]
            else:
                products = products.distinct()
                products = sorted(products, key= lambda x: random.random())

        context = {
            "products": products,
            "top_tags": top_tags,
            "posts": queryset,
        }
        return render(request, "dashboard/view.html", context)

src/sellers/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView

from billing.models import Transaction
from digitalmarket.mixins import LoginRequiredMixin
from products.models import Product

from .forms import NewSellerForm
from .mixins import SellerAccountMixin
from .models import SellerAccount


class SellerProductDetailRedirectView(RedirectView):
    permanent = True
    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()
        

class SellerTransactionListView(SellerAccountMixin, ListView):
	model = Transaction
	template_name = "sellers/transaction_list_view.html"

	def get_queryset(self):
		return self.get_transactions()


class SellerDashboard(SellerAccountMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = "/seller/"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        apply_form = self.get_form() #NewSellerForm()
        account = self.get_account()
        exists = account
        active = None
        context = {}
        if exists:
            active = account.active
        if not exists and not active:
            context["title"] = "Apply for Account"
            context["apply_form"] = apply_form
        elif exists and not active:
            context["title"] = "Account Pending"
        elif exists and active:
            context["title"] = "Seller Dashboard"
            # products = Product.objects.filter(seller=account)
            context["products"] = self.get_products()[:4]
            transactions_today = self.get_transactions_today()
            context["transactions_today"] = transactions_today
            context["today_sales"] = self.get_today_sales()
            context["total_sales"] = self.get_total_sales()
            context["transactions"] = self.get_transactions().exclude(pk__in=transactions_today)[:5]
        else:
            pass

        return render(request, "sellers/dashboard.html", context)

    def form_valid(self, form):
        valid_data = super(SellerDashboard, self).form_valid(form)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data

src/templates/sellers/dashboard.html
{% extends "base.html" %}
{% block content %}

{% include "dashboard/seller_header.html" %}
<!-- you are here: sellers/dashboard.html -->

<div class="container" id="seller-dashboard">
  <div class="page-header">
    <h1>{{ title }}</h1>

  </div>

  {% if apply_form %}
    <p>PLEASE READ THIS TERMS OF USE AGREEMENT (“AGREEMENT” OR “TERMS OF USE”)
      CAREFULLY BEFORE USING THE WEBSITE, MOBILE APPLICATIONS AND SERVICES OFFERED
      BY CONTINUA APPAREL CORPORATION OR ANY OF ITS SUBSIDIARIES (“ONE MORE AGAIN” OR THE “COMPANY”).
      THIS AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF THE WEBSITE
      AT WWW.ONEMOREAGAIN.COM (“WEBSITE”), MOBILE APPLICATIONS, AND SERVICES PROVIDED BY ONE MORE AGAIN
      (COLLECTIVELY, “SERVICES”).</p>

    <p><strong><a href="#">Read our Terms of Agreement</a></strong></p>

    <form method='POST' action=''> {% csrf_token %}
      {{ apply_form.as_p }}
      <br/>
      <input class="btn btn-default" type='submit'/>
    </form>
  {% endif %}

  {% if products %}
    <div class="page-header">
      <a class="btn btn-default pull-right" href="{% url "sellers:product_list" %}">View All </a>
      <h2>Active Listings</h2>
    </div>
      {% include "products/product_result.html" with product_list=products %}
  {% endif %}


  {% if transactions %}
  <div class="page-header">
    <a class="btn btn-default pull-right" href="{% url "sellers:transactions" %}">View All</a>
    <h2>Sales</h2>
  </div>
  <h3>Today's Sales</h3>
    {% include "sellers/transaction_list.html" with transaction_list=transactions_today %}
    <div class="alert alert-success" role="alert"><h4>Today's Sales Total: ${{ today_sales }}</h4></div>

  <h3>Recent Sales</h3>
    {% include "sellers/transaction_list.html" with transaction_list=transactions %}
    <div class="alert alert-success" role="alert"><h4>All Sales Total: ${{ total_sales }}<h4></div>
  <br /><br />
  {% endif %}

</div>
{% endblock %}

src/templates/sellers/product_list_view.html
{% extends "base.html" %}
{% block content %}
{% load get_thumbnail %}

{% include "dashboard/seller_header.html" %}
<!-- You are here: /sellers/product_list_view.html -->

<div class="container">

<div class="page-header">

  <div id="list-sidebar" class="col-sm-4 pull-right">
    <form method="GET" action="">
      <div class="input-group add-on">
        <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}" />
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search" alt="Search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- <ul class="pager">
      <li class="previous"><a href="/seller/">&larr; Back to Dashboard</a></li>
    </ul> -->
    <br />
  </div>

    <h1>Active Listings</h1>

</div>

<div class="row">


  </div><!-- end row -->

  <div id="list-display" class="col-sm-12">
    <br />

    {% for instance in product_list %}
    <div class="row">
      <div class="my-product-instance">

        <a href="{{ instance.get_absolute_url }}" >
          <div class="col-sm-3">
            {% if instance|get_thumbnail:"sd" %}
              <div class="thumbnail">
                <img class="img-responsive" src="{{ instance|get_thumbnail:"sd" }}" alt="{{ instance }}" />
              </div>
              <br />
            {% endif %}
          </div>

          <div class="col-sm-6">
            <h5>{{ instance.brand }}</h5>
            <p>{{ instance }}</p>
            <p><strong>${{ instance.price }}</strong></p>
            <p>Size: {{ instance.size }}</p>
          </div>
        </a>

        <div class="col-sm-3">
          <div class="pull-right">
            <a href="{{ instance.get_edit_url }}" class="btn btn-success">Edit</a>
            <a class="btn btn-info">Delete</a>
          </div>
        </div>

      </div>
    </div><!-- end single product row -->

      {% empty %}
          <p>No products yet!  Check back soon!</p>
      {% endfor %}

  </div>


</div><!-- end container -->
{% endblock content %}

src/templates/sellers/transaction_list.html
<table class="table">
<thead>
  <tr>
    <th>Date/Time</th>
    <th>Product</th>
    <th>Purchased by User</th>
    <th>Price</th>
  </tr>
</thead>
<tbody>
{% for trans in transaction_list %}
  <tr>
    <td>{{ trans.timestamp|timesince }} ago</td>
    <td>{{ trans.product }}</td>
    <td>{{ trans.user }}</td>
    <td>{{ trans.price }}</td>
  </tr>
{% endfor %}
</tbody>
</table>

src/templates/sellers/transaction_list_view.html
{% extends "base.html" %}
{% block content %}

{% include "dashboard/seller_header.html" %}
<!-- You are here: /sellers/transaction_list_view.html -->

<div class="container">

  <div class="page-header">
    <h1>Sold Items</h1>
  </div>

<div class="row">

  <div id="list-display">
    {% include "sellers/transaction_list.html" with transaction_list=object_list %}
  </div>

</div><!-- end row -->

</div><!-- end container -->
{% endblock content %}